#pragma once

#include "CoreMinimal.h"
#include "Calysto/EFCalystoDungeonTypes.h"
#include "Engine/DataAsset.h"
#include "EFCalystoDungeonDirectorPolicy.generated.h"

class AActor;

USTRUCT(BlueprintType)
struct EFPROCEDURALRUNTIME_API FEFCalystoDirectorLimits
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "18", ClampMax = "30"))
	int32 MinDungeonEdge = 18;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "18", ClampMax = "30"))
	int32 MaxDungeonEdge = 30;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0", ClampMax = "25"))
	int32 MaxEnemies = 25;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0", ClampMax = "8"))
	int32 MaxFood = 8;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0", ClampMax = "3"))
	int32 MaxChests = 3;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0", ClampMax = "4"))
	int32 MaxLoot = 4;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0", ClampMax = "4"))
	int32 MaxSpecialEvents = 2;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "1", ClampMax = "36"))
	int32 MaxDirectorActors = 36;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0.20", ClampMax = "0.50"))
	float MinCandidateAnchorDensity = 0.20f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0.20", ClampMax = "0.50"))
	float MaxCandidateAnchorDensity = 0.50f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0.30", ClampMax = "0.70"))
	float MinSidePathChance = 0.30f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "0.30", ClampMax = "0.70"))
	float MaxSidePathChance = 0.70f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "4", ClampMax = "8"))
	int32 RoomMinSize = 4;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Limits", meta = (ClampMin = "4", ClampMax = "8"))
	int32 RoomMaxSize = 8;
};

USTRUCT(BlueprintType)
struct EFPROCEDURALRUNTIME_API FEFCalystoProgressionPolicy
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.1"))
	float LayoutTau = 12.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.1"))
	float ThreatTau = 10.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	float StartSizeMode = 20.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	float EndSizeMode = 30.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "6.0"))
	float SizeHalfRange = 2.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float StartEnemyPresence = 0.70f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float EndEnemyPresence = 0.95f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	float StartEnemyCountMode = 4.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	float EndEnemyCountMode = 20.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0"))
	float EnemyCountLowerOffset = 4.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0"))
	float EnemyCountUpperOffset = 5.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0"))
	float StartThreatBudget = 6.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0"))
	float EndThreatBudget = 50.0f;

	/** Symmetric fractional PERT range around the saturating threat-budget mode. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "0.50"))
	float ThreatBudgetRelativeRange = 0.15f;

	/** Maximum absolute cadence bias generated by the isolated Pacing domain. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "0.25"))
	float PacingAmplitude = 0.10f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float StartFoodPresence = 0.75f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float EndFoodPresence = 0.55f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float StartChestPresence = 0.25f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float EndChestPresence = 0.45f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float StartLootPresence = 0.05f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float EndLootPresence = 0.20f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float StartSpecialEventPresence = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float EndSpecialEventPresence = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	FEFCalystoFloatDistribution CandidateAnchorDensity = {0.25f, 0.32f, 0.45f, 4.0f};

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	FEFCalystoFloatDistribution SidePathChance = {0.35f, 0.50f, 0.65f, 4.0f};

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	FEFCalystoIntDistribution FoodCount = {1, 2, 4, 4.0f};

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	FEFCalystoIntDistribution ChestCount = {1, 1, 2, 5.0f};

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	FEFCalystoIntDistribution LootCount = {1, 1, 2, 5.0f};

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Progression")
	FEFCalystoIntDistribution SpecialEventCount = {1, 1, 1, 6.0f};
};

USTRUCT(BlueprintType)
struct EFPROCEDURALRUNTIME_API FEFCalystoEcologyPolicy
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float RunDNAWeight = 0.45f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float SmoothNoiseWeight = 0.35f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float JitterWeight = 0.20f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "2"))
	int32 SmoothNoisePeriod = 6;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "1"))
	int32 MaxConsecutiveStyle = 2;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "1"))
	int32 MaxConsecutiveDominantTheme = 3;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "1"))
	int32 FoodPityAfterEmptyFloors = 2;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "1"))
	int32 ChestPityAfterEmptyFloors = 4;

	/** How strongly the independent Rarity roll reshapes authored catalog weights. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ecology", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float RaritySelectionStrength = 0.75f;
};

USTRUCT(BlueprintType)
struct EFPROCEDURALRUNTIME_API FEFCalystoAdaptationPolicy
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Adaptation")
	float CombatWeight = 0.40f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Adaptation")
	float SurvivalWeight = 0.25f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Adaptation")
	float ResourcesWeight = 0.20f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Adaptation")
	float PaceWeight = 0.15f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Adaptation", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float EMAAlpha = 0.25f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Adaptation", meta = (ClampMin = "0.0", ClampMax = "0.15"))
	float MaximumInfluence = 0.15f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Adaptation", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float DeathPenalty = 0.10f;
};

USTRUCT(BlueprintType)
struct EFPROCEDURALRUNTIME_API FEFCalystoStylePolicy
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Style")
	EEFCalystoDungeonStyle Style = EEFCalystoDungeonStyle::Standard;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Style", meta = (ClampMin = "1", ClampMax = "100"))
	int32 SelectionWeight = 1;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Style", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float ScaleBias = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Style", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float BranchingBias = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Style", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float ThreatBias = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Style", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float AbundanceBias = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Style", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float MysteryBias = 0.0f;
};

USTRUCT(BlueprintType)
struct EFPROCEDURALRUNTIME_API FEFCalystoPopulationCatalogEntry
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog")
	FName StableId = NAME_None;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog")
	bool bEnabled = true;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog", meta = (AssetBundles = "CalystoFloor"))
	TSoftClassPtr<AActor> ActorClass;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog", meta = (ClampMin = "0", ClampMax = "100"))
	int32 BaseWeight = 1;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog", meta = (ClampMin = "0.0"))
	float Cost = 1.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog", meta = (ClampMin = "1"))
	int64 MinimumFloor = 1;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog", meta = (ClampMin = "1", ClampMax = "25"))
	int32 MaxPerFloor = 25;

	/** Normalized rarity target used only by the isolated Rarity RNG domain. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float Rarity = 0.0f;

	/** Full intervening floors during which this StableId cannot be selected again. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalog", meta = (ClampMin = "0", ClampMax = "100"))
	int32 CooldownFloors = 0;
};

USTRUCT(BlueprintType)
struct EFPROCEDURALRUNTIME_API FEFCalystoThemeCatalogEntry
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Themes")
	FName StableId = NAME_None;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Themes", meta = (AssetBundles = "CalystoFloor"))
	TSoftObjectPtr<UObject> RoomType;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Themes", meta = (ClampMin = "1", ClampMax = "100"))
	int32 BaseWeight = 1;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Themes", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float BiasAxis = 0.0f;
};

/** The sole V3 authoring authority. Runtime never modifies or saves this asset. */
UCLASS(BlueprintType)
class EFPROCEDURALRUNTIME_API UEFCalystoDungeonDirectorPolicy : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UEFCalystoDungeonDirectorPolicy();

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Identity")
	int32 SchemaVersion = 3;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Identity")
	int32 GeneratorVersion = 3;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Identity")
	FName PolicyId = TEXT("CalystoDungeonDirectorV3");

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Policy")
	FEFCalystoDirectorLimits Limits;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Policy")
	FEFCalystoProgressionPolicy Progression;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Policy")
	FEFCalystoEcologyPolicy Ecology;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Policy")
	FEFCalystoAdaptationPolicy Adaptation;

	/** Only sizes proven by the runtime size matrix may be selected. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Policy")
	TArray<int32> ValidatedDungeonSizes;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Policy", meta = (TitleProperty = "Style"))
	TArray<FEFCalystoStylePolicy> Styles;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogs", meta = (TitleProperty = "StableId", AssetBundles = "CalystoFloor"))
	TArray<FEFCalystoPopulationCatalogEntry> EnemyCatalog;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogs", meta = (TitleProperty = "StableId", AssetBundles = "CalystoFloor"))
	TArray<FEFCalystoPopulationCatalogEntry> FoodCatalog;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogs", meta = (TitleProperty = "StableId", AssetBundles = "CalystoFloor"))
	TArray<FEFCalystoPopulationCatalogEntry> ChestCatalog;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogs", meta = (TitleProperty = "StableId", AssetBundles = "CalystoFloor"))
	TArray<FEFCalystoPopulationCatalogEntry> LootCatalog;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogs", meta = (TitleProperty = "StableId", AssetBundles = "CalystoFloor"))
	TArray<FEFCalystoPopulationCatalogEntry> SpecialEventCatalog;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogs", meta = (TitleProperty = "StableId", AssetBundles = "CalystoFloor"))
	TArray<FEFCalystoThemeCatalogEntry> ThemeCatalog;

	bool Validate(FString& OutError) const;

	UFUNCTION(BlueprintPure, Category = "EF|Calysto Dungeon")
	bool ValidatePolicy() const
	{
		FString ValidationError;
		return Validate(ValidationError);
	}

	/** Canonical SHA-256 used by the Director's deterministic domain tuple. */
	UFUNCTION(BlueprintPure, Category = "EF|Calysto Dungeon")
	FString GetPolicyHash() const;

	/**
	 * Computes the exact post-promotion hash on a transient clone. The source
	 * asset is never dirtied or saved. Invalid candidate lists return empty.
	 */
	UFUNCTION(BlueprintPure, Category = "EF|Calysto Dungeon|Automation")
	FString GetPolicyHashWithValidatedDungeonSizes(const TArray<int32>& CandidateSizes) const;

	FString BuildCanonicalString() const;
};
