#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "GameplayTagContainer.h"
#include "Misc/SecureHash.h"
#include "EFClothingGarmentCatalog.generated.h"

class USkeletalMesh;

/** Runtime backend selected per garment/body pair by the authored catalog. */
UENUM(BlueprintType)
enum class EEFClothingSurfaceBackend : uint8
{
	/** Geometry-compiled correspondence, certified weights and adaptive clearance. */
	GeometryFitFallback UMETA(DisplayName = "Geometry Fit Fallback"),

	/** Final GPU surface-wrap backend; rows can opt in as its cooked graph becomes available. */
	SurfaceWrapGPU UMETA(DisplayName = "Surface Wrap GPU"),

	Disabled UMETA(Hidden)
};

/** Authored override for the compiler's automatic tight/loose classification. */
UENUM(BlueprintType)
enum class EEFClothingFitPolicy : uint8
{
	Auto,
	Tight,
	Hybrid,
	Loose,
	Rigid
};

/**
 * Authored source of truth for meshes that EF Clothing Morph is allowed to manage.
 * A garment can have separate Female/Male rows without changing runtime code.
 */
USTRUCT(BlueprintType)
struct EFCLOTHINGMORPHRUNTIME_API FEFClothingGarmentRow : public FTableRowBase
{
	GENERATED_BODY()

	/** Immutable authoring/runtime identity. Array order is presentation-only. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "01 | Identity", meta = (DisplayName = "Garment Index / ID", ToolTip = "Stable unique identity. Do not change it after compiling this garment."))
	FName GarmentId = NAME_None;

	/** Friendly name shown by the Clothing Director. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "01 | Identity")
	FText DisplayName;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "01 | Identity", meta = (DisplayName = "Enabled / Consider As Clothing"))
	bool bEnabled = true;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "01 | Identity", meta = (DisplayName = "Clothing Mesh (Source)", ToolTip = "Select the original garment mesh used by inventory/ACF. Never select an SK_... generated by EF Clothing Morph."))
	TSoftObjectPtr<USkeletalMesh> SourceGarment;

	/** Exact visible body surface for this compiled row (Female now, Male later). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "01 | Identity", meta = (DisplayName = "Body Surface"))
	TSoftObjectPtr<USkeletalMesh> BodySurface;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "02 | Surface Fit")
	EEFClothingSurfaceBackend Backend = EEFClothingSurfaceBackend::SurfaceWrapGPU;

	/** Auto classifies connected garment regions; explicit modes remain available for authoring exceptions. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "02 | Surface Fit")
	EEFClothingFitPolicy FitPolicy = EEFClothingFitPolicy::Auto;

	/** Semantic coverage used by gameplay/UI and future body-region proxy masks. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "03 | Coverage")
	FGameplayTagContainer CoverageTags;

	/**
	 * Body material slots hidden only on the live body component while this garment
	 * is applied. Visibility is reference-counted and restored exactly on unequip.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "03 | Coverage")
	TArray<FName> HiddenBodyMaterialSlots;

	/**
	 * Body sections that must not participate in the compiler's closest-surface,
	 * clearance or skin-weight projection. This is distinct from visual hiding:
	 * auxiliary anatomy can be hidden at runtime and also excluded from the
	 * mathematical body envelope without hard-coding a garment or DAZ product.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "99 | Advanced Surface Exclusions", meta = (AdvancedDisplay))
	TArray<FName> ExcludedBodySurfaceMaterialSlots;

	/**
	 * Root bones of optional anatomy branches that must never drive this garment.
	 * The compiler redirects their influence to the nearest non-excluded,
	 * hierarchy-compatible ancestor on the generated EF_AutoFit profile only.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "99 | Advanced Surface Exclusions", meta = (AdvancedDisplay))
	TArray<FName> ExcludedBodyBoneBranches;

	/** Body morph namespaces belonging to an excluded accessory/graft. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "99 | Advanced Surface Exclusions", meta = (AdvancedDisplay))
	TArray<FString> ExcludedBodyMorphPrefixes;

	/** Optional authored floor; it is always rounded upward to a compiler-certified tier. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "02 | Surface Fit", meta = (ClampMin = "1.0", ClampMax = "2.0", AdvancedDisplay))
	float MinimumClearanceMultiplier = 1.0f;

	/** Negative means compiler-selected from geometry/fabric data; otherwise an absolute cm floor. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "02 | Surface Fit", meta = (ClampMin = "-1.0", ClampMax = "5.0", UIMin = "-1.0", UIMax = "2.0", Units = "cm", DisplayName = "Fabric Clearance (cm; -1 = Auto)", AdvancedDisplay))
	float FabricClearanceCm = -1.0f;

	/** Enables this garment's topology-free runtime clearance override. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "04 | Runtime Offset", meta = (DisplayName = "Enable This Garment Offset", ToolTip = "When disabled, Extra Surface Offset for this garment is ignored."))
	bool bEnableRuntimeTuning = true;

	/** Extra outward clearance applied after skinning and morphs, in centimeters. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "04 | Runtime Offset", meta = (ClampMin = "0.0", ClampMax = "0.35", UIMin = "0.0", UIMax = "0.35", Units = "cm", DisplayName = "Extra Surface Offset (cm)", ToolTip = "Safe outward offset applied after animation and morphs. It is clamped at runtime and never invalidates or recompiles the garment.", EditCondition = "bEnableRuntimeTuning"))
	float AdditionalClearanceCm = 0.0f;

	/** Hidden schema-1 field retained only until legacy DataTables are retired. */
	UPROPERTY()
	float RuntimeOffsetCm = 0.0f;

	/** Optional human-facing note; it has no runtime or compiler effect. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "05 | Notes", meta = (MultiLine = "true"))
	FText Notes;

	/** Negative means compiler-selected; otherwise the hard one-frame outward correction bound. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "02 | Surface Fit", meta = (ClampMin = "-1.0", ClampMax = "10.0", UIMin = "-1.0", UIMax = "10.0", Units = "cm", DisplayName = "Maximum Correction (cm; -1 = Auto)", AdvancedDisplay))
	float MaximumCorrectionCm = -1.0f;

	/** Missing or stale body/garment LOD bindings must never expose the uncorrected garment. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "02 | Surface Fit", meta = (AdvancedDisplay))
	bool bFailClosedOnMissingLOD = true;

	/** Hash of compile-relevant authoring only; runtime offsets and notes are excluded. */
	FString BuildCompileFingerprint() const
	{
		auto CanonicalNames = [](const TArray<FName>& Values)
		{
			TArray<FString> Result;
			for (const FName Value : Values)
			{
				if (!Value.IsNone())
				{
					Result.AddUnique(Value.ToString());
				}
			}
			Result.Sort();
			return FString::Join(Result, TEXT(","));
		};
		auto CanonicalStrings = [](const TArray<FString>& Values)
		{
			TArray<FString> Result;
			for (const FString& Value : Values)
			{
				if (!Value.IsEmpty())
				{
					Result.AddUnique(Value);
				}
			}
			Result.Sort();
			return FString::Join(Result, TEXT(","));
		};

		TArray<FGameplayTag> Tags;
		CoverageTags.GetGameplayTagArray(Tags);
		Tags.Sort([](const FGameplayTag& A, const FGameplayTag& B)
		{
			return A.GetTagName().LexicalLess(B.GetTagName());
		});
		TArray<FString> TagStrings;
		for (const FGameplayTag Tag : Tags)
		{
			TagStrings.Add(Tag.ToString());
		}

		const FString Canonical = FString::Printf(
			TEXT("Backend=%d|Fit=%d|Coverage=%s|Hidden=%s|ExcludedSurface=%s|ExcludedBones=%s|ExcludedMorphs=%s|MinMultiplier=%.6f|Fabric=%.6f|MaxCorrection=%.6f|FailClosedLOD=%d"),
			static_cast<int32>(Backend),
			static_cast<int32>(FitPolicy),
			*FString::Join(TagStrings, TEXT(",")),
			*CanonicalNames(HiddenBodyMaterialSlots),
			*CanonicalNames(ExcludedBodySurfaceMaterialSlots),
			*CanonicalNames(ExcludedBodyBoneBranches),
			*CanonicalStrings(ExcludedBodyMorphPrefixes),
			MinimumClearanceMultiplier,
			FabricClearanceCm,
			MaximumCorrectionCm,
			bFailClosedOnMissingLOD ? 1 : 0);
		return FMD5::HashAnsiString(*Canonical);
	}
};

/**
 * Legacy read-only migration schema for DT_EFClothingGarmentTuning. Runtime no
 * longer consumes this struct; it remains registered so the one-time Director
 * migration can deserialize and retire the old table safely.
 */
USTRUCT()
struct EFCLOTHINGMORPHRUNTIME_API FEFClothingGarmentTuningRow : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY()
	bool bEnableTuning = true;

	UPROPERTY()
	float AdditionalClearanceCm = 0.0f;

	UPROPERTY()
	FText Notes;
};
